// Generated by gleedoc - do not edit manually

import fixtures/store.{get, insert, new}
import gleam/int
import gleam/option.{None, Some}

// From: dev/fixtures/store.gleam:22
pub fn get_1_test() {
  let s = new() |> insert("x", 42)

  assert get(s, "x") == Some(42)
  assert get(s, "y") == None

  assert get(s, "x")
    |> option.unwrap(42)
    |> int.to_string
    == "42"
}
