// Generated by gleedoc - do not edit manually

import fixtures/store.{get, insert, new}
import gleam/option.{None, Some}

// From: test/fixtures/store.gleam:21
pub fn get_1_test() {
  let s = new() |> insert("x", 42)
  
  assert get(s, "x") == Some(42)
  assert get(s, "y") == None
}