// Generated by gleedoc - do not edit manually

import fixtures/bear.{Bear, order_asc_by_name}
import gleam/order

// From: dev/fixtures/bear.gleam:16
pub fn order_asc_by_name_1_test() {
  let alpha = Bear(id: 1, name: "Alpha", kind: "Grizzly", hibernating: False)
  let beta = Bear(id: 2, name: "Beta", kind: "Polar", hibernating: True)

  assert order_asc_by_name(alpha, beta) == order.Lt
}

// From: dev/fixtures/bear.gleam:25
pub fn order_asc_by_name_2_test() {
  let alpha = Bear(id: 1, name: "Zara", kind: "Grizzly", hibernating: False)
  let beta = Bear(id: 2, name: "Zara", kind: "Polar", hibernating: True)

  assert order_asc_by_name(alpha, beta) == order.Eq
}

// From: dev/fixtures/bear.gleam:32
pub fn order_asc_by_name_3_test() {
  let alpha = Bear(id: 1, name: "Zara", kind: "Grizzly", hibernating: False)
  let beta = Bear(id: 2, name: "Alpha", kind: "Polar", hibernating: True)

  assert order_asc_by_name(alpha, beta) == order.Gt
}
