// Generated by gleedoc - do not edit manually

import fixtures/example.{User, add, find, greet, multiply}
import gleam/dict
import gleam/result

// From: test/fixtures/example.gleam:6
pub fn add_1_test() {
  let result = add(1, 2)
  let assert True = result == 3
}

// From: test/fixtures/example.gleam:16
pub fn multiply_2_test() {
  let result = multiply(3, 4)
  let assert True = result == 12
}

// From: test/fixtures/example.gleam:26
pub fn greet_3_test() {
  let msg = greet("Alice")
  let assert True = msg == "Hello, Alice!"
}

// From: test/fixtures/example.gleam:40
pub fn find_4_test() {
  let john = User("John", "Doe")
  let bill = User("Bill", "Wilson")
  
  let users =
  [#("bill_wilson", bill), #("john_doe", john)]
  |> dict.from_list
  
  assert users |> find("hello") == User("", "")
  assert users |> find("john_doe") == john
}