// Generated by gleedoc - do not edit manually

import fixtures/int.{
  absolute_value, add, base_parse, bitwise_and, bitwise_exclusive_or,
  bitwise_not, bitwise_or, bitwise_shift_left, bitwise_shift_right, clamp,
  compare, divide, floor_divide, is_even, is_odd, max, min, modulo, multiply,
  negate, parse, power, product, random, range, remainder, square_root, subtract,
  sum, to_base16, to_base2, to_base36, to_base8, to_base_string, to_float,
  to_string,
}
import gleam/float
import gleam/list
import gleam/order.{type Order, Eq, Gt, Lt}

// From: test/fixtures/int.gleam:20
pub fn absolute_value_1_test() {
  assert absolute_value(-12) == 12
}

// From: test/fixtures/int.gleam:24
pub fn absolute_value_2_test() {
  assert absolute_value(10) == 10
}

// From: test/fixtures/int.gleam:40
pub fn power_3_test() {
  assert power(2, -1.0) == Ok(0.5)
}

// From: test/fixtures/int.gleam:44
pub fn power_4_test() {
  assert power(2, 2.0) == Ok(4.0)
}

// From: test/fixtures/int.gleam:48
pub fn power_5_test() {
  assert power(8, 1.5) == Ok(22.627416997969522)
}

// From: test/fixtures/int.gleam:52
pub fn power_6_test() {
  assert 4 |> power(of: 2.0) == Ok(16.0)
}

// From: test/fixtures/int.gleam:56
pub fn power_7_test() {
  assert power(-1, 0.5) == Error(Nil)
}

// From: test/fixtures/int.gleam:70
pub fn square_root_8_test() {
  assert square_root(4) == Ok(2.0)
}

// From: test/fixtures/int.gleam:74
pub fn square_root_9_test() {
  assert square_root(-16) == Error(Nil)
}

// From: test/fixtures/int.gleam:88
pub fn module_10_test() {
  assert parse("2") == Ok(2)
}

// From: test/fixtures/int.gleam:92
pub fn module_11_test() {
  assert parse("ABC") == Error(Nil)
}

// From: test/fixtures/int.gleam:105
pub fn base_parse_12_test() {
  assert base_parse("10", 2) == Ok(2)
}

// From: test/fixtures/int.gleam:109
pub fn base_parse_13_test() {
  assert base_parse("30", 16) == Ok(48)
}

// From: test/fixtures/int.gleam:113
pub fn base_parse_14_test() {
  assert base_parse("1C", 36) == Ok(48)
}

// From: test/fixtures/int.gleam:117
pub fn base_parse_15_test() {
  assert base_parse("48", 1) == Error(Nil)
}

// From: test/fixtures/int.gleam:121
pub fn base_parse_16_test() {
  assert base_parse("48", 37) == Error(Nil)
}

// From: test/fixtures/int.gleam:140
pub fn module_17_test() {
  assert to_string(2) == "2"
}

// From: test/fixtures/int.gleam:154
pub fn to_base_string_18_test() {
  assert to_base_string(2, 2) == Ok("10")
}

// From: test/fixtures/int.gleam:158
pub fn to_base_string_19_test() {
  assert to_base_string(48, 16) == Ok("30")
}

// From: test/fixtures/int.gleam:162
pub fn to_base_string_20_test() {
  assert to_base_string(48, 36) == Ok("1C")
}

// From: test/fixtures/int.gleam:166
pub fn to_base_string_21_test() {
  assert to_base_string(48, 1) == Error(Nil)
}

// From: test/fixtures/int.gleam:170
pub fn to_base_string_22_test() {
  assert to_base_string(48, 37) == Error(Nil)
}

// From: test/fixtures/int.gleam:189
pub fn to_base2_23_test() {
  assert to_base2(2) == "10"
}

// From: test/fixtures/int.gleam:201
pub fn to_base8_24_test() {
  assert to_base8(15) == "17"
}

// From: test/fixtures/int.gleam:213
pub fn to_base16_25_test() {
  assert to_base16(48) == "30"
}

// From: test/fixtures/int.gleam:225
pub fn to_base36_26_test() {
  assert to_base36(48) == "1C"
}

// From: test/fixtures/int.gleam:237
pub fn module_27_test() {
  assert to_float(5) == 5.0
}

// From: test/fixtures/int.gleam:241
pub fn module_28_test() {
  assert to_float(0) == 0.0
}

// From: test/fixtures/int.gleam:245
pub fn module_29_test() {
  assert to_float(-3) == -3.0
}

// From: test/fixtures/int.gleam:261
pub fn clamp_30_test() {
  assert clamp(40, min: 50, max: 60) == 50
}

// From: test/fixtures/int.gleam:265
pub fn clamp_31_test() {
  assert clamp(40, min: 50, max: 30) == 40
}

// From: test/fixtures/int.gleam:280
pub fn compare_32_test() {
  assert compare(2, 3) == Lt
}

// From: test/fixtures/int.gleam:286
pub fn compare_33_test() {
  assert compare(4, 3) == Gt
}

// From: test/fixtures/int.gleam:292
pub fn compare_34_test() {
  assert compare(3, 3) == Eq
}

// From: test/fixtures/int.gleam:313
pub fn min_35_test() {
  assert min(2, 3) == 2
}

// From: test/fixtures/int.gleam:328
pub fn max_36_test() {
  assert max(2, 3) == 3
}

// From: test/fixtures/int.gleam:343
pub fn is_even_37_test() {
  assert is_even(2)
}

// From: test/fixtures/int.gleam:347
pub fn is_even_38_test() {
  assert !is_even(3)
}

// From: test/fixtures/int.gleam:359
pub fn is_odd_39_test() {
  assert is_odd(3)
}

// From: test/fixtures/int.gleam:363
pub fn is_odd_40_test() {
  assert !is_odd(2)
}

// From: test/fixtures/int.gleam:375
pub fn negate_41_test() {
  assert negate(1) == -1
}

// From: test/fixtures/int.gleam:387
pub fn sum_42_test() {
  assert sum([1, 2, 3]) == 6
}

// From: test/fixtures/int.gleam:406
pub fn product_43_test() {
  assert product([2, 3, 4]) == 24
}

// From: test/fixtures/int.gleam:427
pub fn random_44_test() {
  random(10)
  // -> 4
}

// From: test/fixtures/int.gleam:432
pub fn random_45_test() {
  random(1)
  // -> 0
}

// From: test/fixtures/int.gleam:437
pub fn random_46_test() {
  random(-1)
  // -> -1
}

// From: test/fixtures/int.gleam:455
pub fn divide_47_test() {
  assert divide(0, 1) == Ok(0)
}

// From: test/fixtures/int.gleam:459
pub fn divide_48_test() {
  assert divide(1, 0) == Error(Nil)
}

// From: test/fixtures/int.gleam:463
pub fn divide_49_test() {
  assert divide(5, 2) == Ok(2)
}

// From: test/fixtures/int.gleam:467
pub fn divide_50_test() {
  assert divide(-99, 2) == Ok(-49)
}

// From: test/fixtures/int.gleam:488
pub fn remainder_51_test() {
  assert remainder(3, 2) == Ok(1)
}

// From: test/fixtures/int.gleam:492
pub fn remainder_52_test() {
  assert remainder(1, 0) == Error(Nil)
}

// From: test/fixtures/int.gleam:496
pub fn remainder_53_test() {
  assert remainder(10, -1) == Ok(0)
}

// From: test/fixtures/int.gleam:500
pub fn remainder_54_test() {
  assert remainder(13, by: 3) == Ok(1)
}

// From: test/fixtures/int.gleam:504
pub fn remainder_55_test() {
  assert remainder(-13, by: 3) == Ok(-1)
}

// From: test/fixtures/int.gleam:508
pub fn remainder_56_test() {
  assert remainder(13, by: -3) == Ok(1)
}

// From: test/fixtures/int.gleam:512
pub fn remainder_57_test() {
  assert remainder(-13, by: -3) == Ok(-1)
}

// From: test/fixtures/int.gleam:533
pub fn modulo_58_test() {
  assert modulo(3, 2) == Ok(1)
}

// From: test/fixtures/int.gleam:537
pub fn modulo_59_test() {
  assert modulo(1, 0) == Error(Nil)
}

// From: test/fixtures/int.gleam:541
pub fn modulo_60_test() {
  assert modulo(10, -1) == Ok(0)
}

// From: test/fixtures/int.gleam:545
pub fn modulo_61_test() {
  assert modulo(13, by: 3) == Ok(1)
}

// From: test/fixtures/int.gleam:549
pub fn modulo_62_test() {
  assert modulo(-13, by: 3) == Ok(2)
}

// From: test/fixtures/int.gleam:553
pub fn modulo_63_test() {
  assert modulo(13, by: -3) == Ok(-2)
}

// From: test/fixtures/int.gleam:581
pub fn floor_divide_64_test() {
  assert floor_divide(1, 0) == Error(Nil)
}

// From: test/fixtures/int.gleam:585
pub fn floor_divide_65_test() {
  assert floor_divide(5, 2) == Ok(2)
}

// From: test/fixtures/int.gleam:589
pub fn floor_divide_66_test() {
  assert floor_divide(6, -4) == Ok(-2)
}

// From: test/fixtures/int.gleam:593
pub fn floor_divide_67_test() {
  assert floor_divide(-99, 2) == Ok(-50)
}

// From: test/fixtures/int.gleam:615
pub fn add_68_test() {
  assert add(1, 2) == 3
}

// From: test/fixtures/int.gleam:619
pub fn add_69_test() {
  assert list.fold([1, 2, 3], 0, add) == 6
}

// From: test/fixtures/int.gleam:624
pub fn add_70_test() {
  assert 3 |> add(2) == 5
}

// From: test/fixtures/int.gleam:639
pub fn multiply_71_test() {
  assert multiply(2, 4) == 8
}

// From: test/fixtures/int.gleam:643
pub fn multiply_72_test() {
  assert list.fold([2, 3, 4], 1, multiply) == 24
}

// From: test/fixtures/int.gleam:649
pub fn multiply_73_test() {
  assert 3 |> multiply(2) == 6
}

// From: test/fixtures/int.gleam:664
pub fn subtract_74_test() {
  assert subtract(3, 1) == 2
}

// From: test/fixtures/int.gleam:668
pub fn subtract_75_test() {
  assert list.fold([1, 2, 3], 10, subtract) == 4
}

// From: test/fixtures/int.gleam:674
pub fn subtract_76_test() {
  assert 3 |> subtract(2) == 1
}

// From: test/fixtures/int.gleam:678
pub fn subtract_77_test() {
  assert 3 |> subtract(2, _) == -1
}

// From: test/fixtures/int.gleam:794
pub fn range_78_test() {
  assert range(from: 0, to: 3, with: "", run: fn(acc, i) { acc <> to_string(i) })
    == "012"
}

// From: test/fixtures/int.gleam:802
pub fn range_79_test() {
  assert range(from: 1, to: -2, with: [], run: list.prepend) == [-1, 0, 1]
}
