import gleam/list
import gleam/string
import gleedoc/internal/scan
import simplifile

const bear_fixture = "dev/fixtures/bear.gleam"

const store_fixture = "dev/fixtures/store.gleam"

// ---------------------------------------------------------------------------
// public_names
// ---------------------------------------------------------------------------

pub fn scan_public_names_functions_test() {
  let assert Ok(names) = scan.public_names(bear_fixture, read(bear_fixture))
  assert list.contains(names, "order_asc_by_name")
}

pub fn scan_public_names_types_test() {
  let assert Ok(names) = scan.public_names(bear_fixture, read(bear_fixture))
  assert list.contains(names, "Bear")
}

pub fn scan_public_names_no_private_test() {
  let assert Ok(names) = scan.public_names(store_fixture, read(store_fixture))
  // All of new, insert, get, Store are public — nothing private to leak, but
  // the count must exactly match the three pub fns + one pub type.
  assert list.length(names) == 4
}

// ---------------------------------------------------------------------------
// module_imports — plain imports (no unqualified names)
// ---------------------------------------------------------------------------

pub fn scan_module_imports_plain_test() {
  let assert Ok(imports) = scan.module_imports(bear_fixture, read(bear_fixture))
  assert list.contains(imports, "import gleam/order")
  assert list.contains(imports, "import gleam/string")
}

// ---------------------------------------------------------------------------
// module_imports — unqualified value imports
// ---------------------------------------------------------------------------

pub fn scan_module_imports_unqualified_value_test() {
  // gleam/option is imported as: import gleam/option.{type Option, None, Some}
  // None and Some are values and must NOT be prefixed with `type `.
  let assert Ok(imports) =
    scan.module_imports(store_fixture, read(store_fixture))
  let assert Ok(option_import) =
    list.find(imports, fn(i) {
      i == "import gleam/option.{type Option, None, Some}"
    })
  assert option_import == "import gleam/option.{type Option, None, Some}"
}

// ---------------------------------------------------------------------------
// module_imports — unqualified type imports must carry `type ` prefix
// ---------------------------------------------------------------------------

pub fn scan_module_imports_unqualified_type_prefix_test() {
  // gleam/dict is imported as: import gleam/dict.{type Dict}
  // Dict is a type and must be rendered as `type Dict`, not plain `Dict`.
  let assert Ok(imports) =
    scan.module_imports(store_fixture, read(store_fixture))
  let assert Ok(dict_import) =
    list.find(imports, fn(i) {
      i == "import gleam/dict.{type Dict}" || i == "import gleam/dict.{Dict}"
    })
  assert dict_import == "import gleam/dict.{type Dict}"
}

pub fn scan_module_imports_unqualified_type_no_bare_name_test() {
  // Ensure the bare (incorrect) form `import gleam/dict.{Dict}` is never produced.
  let assert Ok(imports) =
    scan.module_imports(store_fixture, read(store_fixture))
  assert !list.contains(imports, "import gleam/dict.{Dict}")
}

// ---------------------------------------------------------------------------
// remove_unused_imports
// ---------------------------------------------------------------------------

/// A qualified module reference (e.g. `order.Lt`) keeps the import.
pub fn remove_unused_imports_keeps_qualified_module_test() {
  let src =
    "// Generated by gleedoc - do not edit manually"
    <> "\n"
    <> "\n"
    <> "import fixtures/bear.{Bear, order_asc_by_name}"
    <> "\n"
    <> "import gleam/order"
    <> "\n"
    <> "import gleam/string"
    <> "\n"
    <> "\n"
    <> "pub fn order_asc_by_name_1_test() {"
    <> "\n"
    <> "  let alpha = Bear(id: 1, name: \"Alpha\", kind: \"Grizzly\", hibernating: False)"
    <> "\n"
    <> "  assert order_asc_by_name(alpha, alpha) == order.Lt"
    <> "\n"
    <> "}"
    <> "\n"

  let result = scan.remove_unused_imports(src)

  // gleam/order is used as `order.Lt` — must be kept
  assert string.contains(result, "import gleam/order")
  // gleam/string is never referenced — must be removed
  assert !string.contains(result, "import gleam/string")
}

/// An unqualified value import is kept when the name appears in a function body.
pub fn remove_unused_imports_keeps_unqualified_value_test() {
  let src =
    "// Generated by gleedoc"
    <> "\n"
    <> "\n"
    <> "import gleam/option.{None, Some}"
    <> "\n"
    <> "import gleam/string"
    <> "\n"
    <> "\n"
    <> "pub fn example_test() {"
    <> "\n"
    <> "  assert Some(1) == Some(1)"
    <> "\n"
    <> "  assert None == None"
    <> "\n"
    <> "}"
    <> "\n"

  let result = scan.remove_unused_imports(src)

  // Some and None are used — the import must be kept (with both names)
  assert string.contains(result, "import gleam/option")
  assert string.contains(result, "Some")
  assert string.contains(result, "None")
  // gleam/string is unused
  assert !string.contains(result, "import gleam/string")
}

/// An unqualified constructor that is used in a pattern is kept.
pub fn remove_unused_imports_keeps_pattern_constructor_test() {
  let src =
    "import gleam/option.{type Option, None, Some}"
    <> "\n"
    <> "\n"
    <> "pub fn pattern_test() {"
    <> "\n"
    <> "  let Some(x) = Some(42)"
    <> "\n"
    <> "  assert x == 42"
    <> "\n"
    <> "}"
    <> "\n"

  let result = scan.remove_unused_imports(src)

  assert string.contains(result, "import gleam/option")
  // `Some` is used; `None` and `type Option` are not used in this body
  assert string.contains(result, "Some")
  assert !string.contains(result, "None")
}

/// An import that contributes nothing used is dropped entirely.
pub fn remove_unused_imports_drops_entire_unused_module_test() {
  let src =
    "import gleam/result"
    <> "\n"
    <> "import gleam/string"
    <> "\n"
    <> "\n"
    <> "pub fn noop_test() {"
    <> "\n"
    <> "  assert 1 == 1"
    <> "\n"
    <> "}"
    <> "\n"

  let result = scan.remove_unused_imports(src)

  assert !string.contains(result, "import gleam/result")
  assert !string.contains(result, "import gleam/string")
}

/// The header comment line is preserved after filtering.
pub fn remove_unused_imports_preserves_header_test() {
  let src =
    "// Generated by gleedoc - do not edit manually"
    <> "\n"
    <> "\n"
    <> "import gleam/string"
    <> "\n"
    <> "\n"
    <> "pub fn noop_test() {"
    <> "\n"
    <> "  assert 1 == 1"
    <> "\n"
    <> "}"
    <> "\n"

  let result = scan.remove_unused_imports(src)

  assert string.starts_with(
    result,
    "// Generated by gleedoc - do not edit manually",
  )
  assert !string.contains(result, "import gleam/string")
}

/// The bear fixture demonstrates the canonical real-world scenario:
/// gleam/string is pulled from the source module but never used in tests.
pub fn remove_unused_imports_bear_fixture_test() {
  let src = read("test/integration/gleedoc/fixtures_bear_gleedoc_test.gleam")
  // gleam/string should have been removed from the committed fixture
  assert !string.contains(src, "import gleam/string")
  // gleam/order must remain because `order.Lt` / `order.Eq` / `order.Gt` are used
  assert string.contains(src, "import gleam/order")
}

fn read(path: String) -> String {
  let assert Ok(src) = simplifile.read(path)
  src
}
