import filepath
import gleam/bool
import gleam/int
import gleam/list
import gleam/option
import gleam/result
import gleam/string
import gleedoc/internal/parse.{type CodeBlock}
import gleedoc/internal/scan
import shellout
import simplifile
import snag

/// Configuration for test generation.
pub type GenerateConfig {
  Config(
    /// Directory to write generated tests to, typically "test"
    output_dir: String,
    /// A list of imports that will automatically be applied to every generated test file
    extra_imports: List(String),
    /// Whether to annotate each generated `assert` with `as "file:line"`,
    /// pointing back to the exact source line of the assertion.
    source_mapped_errors: Bool,
  )
}

/// Generate test files from extracted code blocks.
pub fn generate_tests(
  blocks: List(CodeBlock),
  config: GenerateConfig,
) -> Result(List(String), snag.Snag) {
  // Group blocks by the file they came from
  let by_file = group_by_file(blocks)

  by_file
  |> list.try_map(fn(pair) {
    let #(file, code_blocks) = pair
    let test_file_name = test_file_name(file)
    let output_dir = filepath.join(config.output_dir, "gleedoc")
    let test_path = filepath.join(output_dir, test_file_name)

    use _ <- result.try(
      simplifile.create_directory_all(output_dir)
      |> result.map_error(fn(err) {
        snag.new(
          "Failed to create directory: "
          <> output_dir
          <> " - "
          <> string.inspect(err),
        )
      }),
    )

    // Imports defined in the source file
    let #(public_names, module_imports) = case code_blocks {
      [first, ..] -> #(first.source.public_names, first.source.module_imports)
      [] -> #([], [])
    }

    // Imports to the source module, including all public names
    let module_name = module_name_from_file(file)
    let import_to_source =
      module_name |> generate_import_to_source(public_names)

    // Imports defined in each code block
    let block_imports = code_blocks |> list.flat_map(fn(b) { b.imports })

    // Extra imports defined by user
    let extra_imports =
      config.extra_imports |> list.map(fn(p) { "import " <> p })

    let all_imports =
      [extra_imports, module_imports, block_imports]
      |> list.flatten
      |> list.prepend(import_to_source)
      |> merge_imports

    let test_functions =
      generate_test_functions(code_blocks, config.source_mapped_errors)

    let raw_content =
      string.join(
        ["// Generated by gleedoc - do not edit manually", "", ..all_imports]
          |> list.append(test_functions),
        "\n",
      )

    let content = scan.remove_unused_imports(raw_content) <> "\n"

    use _ <- result.try(
      simplifile.write(test_path, content)
      |> result.map_error(fn(err) {
        snag.new(
          "Failed to write test file: "
          <> test_path
          <> " - "
          <> string.inspect(err),
        )
      }),
    )

    Ok(test_path)
  })
}

pub fn format_tests(output_dir: String) -> Result(String, snag.Snag) {
  shellout.command("gleam", ["format", output_dir], ".", [])
  |> result.map_error(fn(err) {
    snag.new(
      "Failed to format test file: "
      <> output_dir
      <> " - "
      <> string.inspect(err),
    )
  })
}

fn group_by_file(blocks: List(CodeBlock)) -> List(#(String, List(CodeBlock))) {
  blocks
  |> list.fold([], fn(groups, block) {
    let file = block.source.file
    case find_group(groups, file) {
      Ok(#(_, existing)) -> {
        list.map(groups, fn(pair) {
          case pair.0 == file {
            True -> #(file, [block, ..existing])
            False -> pair
          }
        })
      }
      Error(Nil) -> [#(file, [block]), ..groups]
    }
  })
  |> list.map(fn(pair) { #(pair.0, list.reverse(pair.1)) })
}

fn find_group(
  groups: List(#(String, List(CodeBlock))),
  file: String,
) -> Result(#(String, List(CodeBlock)), Nil) {
  list.find(groups, fn(pair) { pair.0 == file })
}

fn module_name_from_file(file: String) -> String {
  file
  |> filepath.split
  |> list.drop(1)
  |> string.join("/")
  |> string.replace(".gleam", "")
}

fn test_file_name(source_file: String) -> String {
  let name =
    source_file
    |> filepath.split
    |> list.drop(1)
    |> string.join("_")
    |> string.replace(".gleam", "")

  name <> "_gleedoc_test.gleam"
}

type Import {
  Import(module: String, names: List(String))
}

fn parse_import(line: String) -> Import {
  let rest = line |> string.trim |> string.drop_start(7) |> string.trim_start
  case string.split_once(rest, ".{") {
    Ok(#(module, names_part)) -> {
      let names =
        names_part
        |> string.replace("}", "")
        |> string.split(",")
        |> list.map(string.trim)
        |> list.filter(fn(s) { s != "" })
      Import(module, names)
    }
    Error(Nil) -> Import(rest, [])
  }
}

fn import_to_string(imp: Import) -> String {
  case imp.names {
    [] -> "import " <> imp.module
    names -> {
      let types =
        names
        |> list.filter(fn(n) { string.starts_with(n, "type ") })
        |> list.sort(string.compare)
      let values =
        names
        |> list.filter(fn(n) { !string.starts_with(n, "type ") })
        |> list.sort(string.compare)
      let names_str = string.join(list.append(types, values), ", ")
      "import " <> imp.module <> ".{" <> names_str <> "}"
    }
  }
}

fn merge_imports(imports: List(String)) -> List(String) {
  imports
  |> list.map(parse_import)
  |> list.fold([], fn(acc, imp) {
    case list_find_import(acc, imp.module) {
      Ok(existing) -> {
        let merged_names = list.unique(list.append(existing.names, imp.names))
        list.map(acc, fn(existing_imp) {
          case existing_imp.module == imp.module {
            True -> Import(..existing_imp, names: merged_names)
            False -> existing_imp
          }
        })
      }
      Error(Nil) -> [imp, ..acc]
    }
  })
  |> list.map(import_to_string)
  |> list.sort(string.compare)
}

fn list_find_import(
  imports: List(Import),
  module: String,
) -> Result(Import, Nil) {
  list.find(imports, fn(imp) { imp.module == module })
}

fn generate_import_to_source(
  module_name: String,
  public_names: List(String),
) -> String {
  case public_names {
    [] -> "import " <> module_name
    _ ->
      "import "
      <> module_name
      <> "."
      <> "{"
      <> string.join(public_names, ", ")
      <> "}"
  }
}

fn generate_test_functions(
  blocks: List(CodeBlock),
  source_mapped_errors: Bool,
) -> List(String) {
  blocks
  |> list.index_map(fn(block, index) {
    generate_test_function(block, index, source_mapped_errors)
  })
}

fn generate_test_function(
  block: CodeBlock,
  index: Int,
  source_mapped_errors: Bool,
) -> String {
  let target_name = option.unwrap(block.source.target, "module")

  let test_func_name =
    sanitize_name(target_name) <> "_" <> int.to_string(index + 1) <> "_test"

  let detailed_target =
    block.source.file
    <> ":"
    <> int.to_string(block.source.start_line + block.doc_line_offset - 1)

  let source_info = "// From: " <> detailed_target

  [
    "",
    source_info,
    "pub fn " <> test_func_name <> "() {",
    to_function_body(
      block.code,
      block.code_line_offsets,
      block.source.file,
      block.source.start_line,
      detailed_target,
      source_mapped_errors,
    ),
    "}",
  ]
  |> string.join("\n")
}

/// Replace characters that aren't valid in function names
fn sanitize_name(name: String) -> String {
  name
  |> string.replace(".", "_")
  |> string.replace("-", "_")
}

fn to_function_body(
  code: String,
  code_line_offsets: List(Int),
  source_file: String,
  source_start_line: Int,
  fallback_target: String,
  source_mapped_errors: Bool,
) -> String {
  // Drop leading/trailing blank lines while keeping `code_line_offsets`
  // aligned with the surviving lines.
  let pairs =
    list.zip(string.split(code, "\n"), pad_offsets(code, code_line_offsets))
    |> list.drop_while(fn(p) { string.trim(p.0) == "" })
    |> list.reverse
    |> list.drop_while(fn(p) { string.trim(p.0) == "" })
    |> list.reverse

  pairs
  |> list.map(fn(pair) {
    let #(line, maybe_offset) = pair
    let line = case string.trim(line) == "" {
      True -> ""
      False -> "  " <> line
    }

    let is_assert = line |> string.trim_start |> string.starts_with("assert")
    use <- bool.guard(when: !is_assert || !source_mapped_errors, return: line)

    let target = case maybe_offset {
      option.Some(offset) ->
        source_file <> ":" <> int.to_string(source_start_line + offset - 1)
      option.None -> fallback_target
    }
    line <> " as \"" <> target <> "\""
  })
  |> string.join("\n")
}

/// Wrap each offset in `Some`, padding with `None`s so the result has the
/// same length as the lines of `code`. Extra offsets are truncated.
fn pad_offsets(code: String, offsets: List(Int)) -> List(option.Option(Int)) {
  let n = code |> string.split("\n") |> list.length
  let wrapped = offsets |> list.map(option.Some)
  let len = list.length(wrapped)
  case len >= n {
    True -> wrapped |> list.take(n)
    False -> list.append(wrapped, list.repeat(option.None, n - len))
  }
}

/// Clean up generated test files.
pub fn clean_generated(output_dir: String) -> Result(Nil, snag.Snag) {
  let dir = filepath.join(output_dir, "gleedoc")
  case simplifile.read_directory(dir) {
    Ok(files) -> {
      files
      |> list.filter(fn(f) { string.ends_with(f, "_gleedoc_test.gleam") })
      |> list.each(fn(f) {
        let path = filepath.join(dir, f)
        let _ = simplifile.delete(path)
        Nil
      })
      Ok(Nil)
    }
    Error(err) -> {
      // If the output dir doesn't exist, that's fine
      case string.inspect(err) {
        "Enoent" -> Ok(Nil)
        _ ->
          Error(snag.new(
            "Failed to clean generated files: " <> string.inspect(err),
          ))
      }
    }
  }
}
