import gleam/int
import gleam/list
import gleam/option.{None, Some}
import gleam/result
import gleam/string
import gleedoc/parse.{type CodeBlock}
import gleedoc/scan
import simplifile
import snag

/// Configuration for test generation.
pub type Config {
  Config(
    /// The module name being tested, e.g. "mymodule"
    module_name: String,
    /// The package name being tested
    package_name: String,
    /// Directory to write generated tests to, typically "test"
    output_dir: String,
  )
}

/// Generate test files from extracted code blocks.
pub fn generate_tests(
  blocks: List(CodeBlock),
  config: Config,
) -> Result(List(String), snag.Snag) {
  // Group blocks by the file they came from
  let by_file = group_by_file(blocks)

  by_file
  |> list.try_map(fn(pair) {
    let #(file, file_blocks) = pair
    let test_file_name = test_file_name(file)
    let test_path = config.output_dir <> "/" <> test_file_name
    let module_name = module_name_from_file(file)

    let imports = unique_imports(file, module_name)
    let test_functions = generate_test_functions(file_blocks)

    let content = string.join(
      [
        "// Generated by gleedoc - do not edit manually",
        "",
        ..imports
      ]
        |> list.append(test_functions),
      "\n",
    )

      use _ <- result.try(
      simplifile.write(test_path, content)
      |> result.map_error(fn(err) {
        snag.new("Failed to write test file: " <> test_path <> " - " <> string.inspect(err))
      }),
    )

    Ok(test_path)
  })
}

fn group_by_file(blocks: List(CodeBlock)) -> List(#(String, List(CodeBlock))) {
  blocks
  |> list.fold([], fn(groups, block) {
    let file = block.source.file
    case find_group(groups, file) {
      Ok(#(_, existing)) -> {
        list.map(groups, fn(pair) {
          case pair.0 == file {
            True -> #(file, [block, ..existing])
            False -> pair
          }
        })
      }
      Error(Nil) -> [#(file, [block]), ..groups]
    }
  })
  |> list.map(fn(pair) { #(pair.0, list.reverse(pair.1)) })
}

fn find_group(groups: List(#(String, List(CodeBlock))), file: String) -> Result(#(String, List(CodeBlock)), Nil) {
  case groups {
    [] -> Error(Nil)
    [#(f, b), ..rest] -> case f == file {
      True -> Ok(#(f, b))
      False -> find_group(rest, file)
    }
  }
}

fn module_name_from_file(file: String) -> String {
  case string.split_once(file, "/") {
    Ok(#(_, rest)) -> string.replace(rest, ".gleam", "")
    Error(Nil) -> string.replace(file, ".gleam", "")
  }
}

fn test_file_name(source_file: String) -> String {
  let name =
    case string.split_once(source_file, "/") {
      Ok(#(_, rest)) -> rest
      Error(Nil) -> source_file
    }
    |> string.replace(".gleam", "")
    |> string.replace("/", "_")

  "gleedoc_generated_" <> name <> "_test.gleam"
}

fn unique_imports(file: String, module_name: String) -> List(String) {
  // Try to read the source file and extract public names for unqualified imports.
  // If parsing fails, fall back to a simple qualified import.
  case simplifile.read(file) {
    Ok(source) -> {
      case scan.public_names(file, source) {
        Ok([]) -> ["import " <> module_name]
        Ok(names) -> {
          let names_str = string.join(names, ", ")
          ["import " <> module_name <> ".{" <> names_str <> "}"]
        }
        Error(_) -> ["import " <> module_name]
      }
    }
    Error(_) -> ["import " <> module_name]
  }
}

fn generate_test_functions(blocks: List(CodeBlock)) -> List(String) {
  blocks
  |> list.index_map(fn(block, index) {
    generate_test_function(block, index)
  })
}

fn generate_test_function(block: CodeBlock, index: Int) -> String {
  let target_name = case block.source.target {
    Some(name) -> name
    None -> "module"
  }

  let func_name =
    "gleedoc_"
    <> sanitize_name(target_name)
    <> "_"
    <> int.to_string(index + 1)
    <> "_test"

  let source_info =
    "// From: "
    <> block.source.file
    <> ":"
    <> int.to_string(block.source.start_line + block.doc_line_offset - 1)

  let code = block.code |> string.trim

  string.join(
    [
      "",
      source_info,
      "pub fn " <> func_name <> "() {",
      "  " <> string.replace(code, "\n", "\n  "),
      "}",
    ],
    "\n",
  )
}

fn sanitize_name(name: String) -> String {
  // Replace characters that aren't valid in function names
  name
  |> string.replace(".", "_")
  |> string.replace("-", "_")
}

/// Clean up generated test files.
pub fn clean_generated(output_dir: String) -> Result(Nil, snag.Snag) {
  case simplifile.read_directory(output_dir) {
    Ok(files) -> {
      files
      |> list.filter(fn(f) { string.starts_with(f, "gleedoc_generated_") && string.ends_with(f, "_test.gleam") })
      |> list.each(fn(f) {
        let path = output_dir <> "/" <> f
        let _ = simplifile.delete(path)
        Nil
      })
      Ok(Nil)
    }
    Error(err) -> {
      // If the output dir doesn't exist, that's fine
      case string.inspect(err) {
        "Enoent" -> Ok(Nil)
        _ -> Error(snag.new("Failed to clean generated files: " <> string.inspect(err)))
      }
    }
  }
}
